import Acer1 from './assets/Images/Hp/Acer/acer 1.jfif'
import Acer2 from './assets/Images/Hp/Acer/acer 2.jfif'
import Acer3 from './assets/Images/Hp/Acer/acer 3.jfif'

import Dell1 from './assets/Images/Dell/dell 1.jpg'
import Dell2 from './assets/Images/Dell/dell 2.jpg'
import Dell3 from './assets/Images/Dell/dell 3.jpg'
import Dell4 from './assets/Images/Dell/dell 4.jpg'
import Dell5 from './assets/Images/Dell/dell 5.jpg'
import Dell6 from './assets/Images/Dell/dell 6.jpg'

import Hp1 from './assets/Images/Hp/hp 1.jfif'
import Hp2 from './assets/Images/Hp/hp 2.jfif'
import Hp3 from './assets/Images/Hp/hp 3.jfif'
import Hp4 from './assets/Images/Hp/hp 4.jfif'
import Hp5 from './assets/Images/Hp/hp 5.jfif'
import Hp6 from './assets/Images/Hp/hp 6.jfif'

import Samsung1 from './assets/Images/Samsung/samsung 1.jfif'
import Samsung2 from './assets/Images/Samsung/samsung 2.jfif'
import Samsung3 from './assets/Images/Samsung/samsung 3.jfif'
import Samsung4 from './assets/Images/Samsung/samsung 4.jfif'
import Samsung5 from './assets/Images/Samsung/samsung 5.jfif'
import Samsung6 from './assets/Images/Samsung/samsung 6.jfif'

import Lenovo1 from './assets/Images/Lenovo/lenovo 1.jfif'
import Lenovo2 from './assets/Images/Lenovo/lenovo 2.jfif'
import Lenovo3 from './assets/Images/Lenovo/lenovo 3.jfif'
import Lenovo4 from './assets/Images/Lenovo/lenovo 2.jfif'
import Lenovo5 from './assets/Images/Lenovo/lenovo 5.jfif'

import Apple1 from './assets/Images/Apple/apple 1.jfif'
import Apple2 from './assets/Images/Apple/apple 2.jfif'
import Apple3 from './assets/Images/Apple/apple 3.jfif'
import Apple4 from './assets/Images/Apple/apple 4.jfif'

export const Data = [
    {
      name: "Dell Inspiron 16 Plus",
      brand: 'Dell',
      screenSize: "16.0\" - 1920x1200",
      processor: "INTEL Ultra i9 185H",
      graphics: "INTEL Arc Graphics XE-cores",
      memory: "16 GB DDR5",
      image: Dell1,
      storage: "512 GB SSD",
      weight: "2.24 Kg / 4.94 lb",
      os: "Windows 11 Home",
      battery: "8.1 - 8.6 h",
      price: "$700",
    },
    {
      name: "Dell Inspiron 14",
      brand: 'Dell',
      screenSize: "14.0\" - 1920x1200",
      processor: "ARM-based Snapdragon X Plus",
      graphics: "ARM Snapdragon X Elite Adreno",
      memory: "16 GB DDR5",
      image: Dell2,
      storage: "512 GB SSD",
      weight: "1.53 Kg / 3.39 lb",
      os: "Windows 11 Home",
      battery: "10.5 - 11.3 h",
      price: "$600",
    },
    {
      name: "Dell Inspiron 16 2-in-1",
      brand: 'Dell',
      screenSize: "16.0\" - 1920x1200",
      processor: "INTEL Ultra i7 155H",
      graphics: "INTEL Iris XE 96 EU",
      memory: "16 GB DDR5",
      image: Dell3,
      storage: "512 GB SSD",
      weight: "2.18 Kg / 4.81 lb",
      os: "Windows 11 Home",
      battery: "10.4 - 11.2 h",
      price: "$750",
    },
    {
      name: "Dell Inspiron 15",
      brand: 'Dell',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL i5-1235U",
      graphics: "INTEL Iris XE 96 EU",
      memory: "16 GB DDR4",
      image: Dell4,
      storage: "1024 GB SSD",
      weight: "1.65 Kg / 3.64 lb",
      os: "Windows 11 Home",
      battery: "3.5 - 3.7 h",
      price: "$610",
    },
    {
      name: "Dell Inspiron 14",
      brand: 'Dell',
      screenSize: "14.0\" - 1920x1200",
      processor: "INTEL i7-1364P",
      graphics: "INTEL Iris XE 96 EU",
      memory: "16 GB DDR5",
      image: Dell5,
      storage: "1024 GB SSD",
      weight: "1.53 Kg / 3.3 lb",
      os: "Windows 11 Home",
      battery: "8.2 - 8.8 h",
      price: "$725",
    },
    {
      name: "Dell Latitude 15",
      brand: 'Dell',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL Ultra i7 155U",
      graphics: "INTEL Graphics XE-cores",
      memory: "32 GB DDR5",
      image: Dell6,
      storage: "1024 GB SSD",
      weight: "1.41 Kg / 3.09 lb",
      os: "Windows 11 Pro",
      battery: "7.2 - 7.7 h",
      price: "$680",
    },
    {
      name: "Dell Inspiron 16",
      brand: 'Hp',
      screenSize: "16.0\" - 1920x1200",
      processor: "AMD Ryzen 7 5700",
      graphics: "AMD Radeon Graphics",
      memory: "16 GB DDR4",
      image: Hp1,
      storage: "512 GB SSD",
      weight: "1.87 Kg / 4.12 lb",
      os: "Windows 11 Home",
      battery: "9.6 h",
      price: "$700",
    },
    {
      name: "Dell Vostro 15",
      brand: 'Hp',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL i7-1255U",
      graphics: "INTEL Iris XE 96 EU",
      memory: "16 GB DDR5",
      image: Hp2,
      storage: "512 GB SSD",
      weight: "1.65 Kg / 3.64 lb",
      os: "Windows 11 Home",
      battery: "4.5 - 4.7 h",
      price: "$648",
    },
    {
      name: "Dell Inspiron 14 2-in-1",
      brand: 'Hp',
      screenSize: "14.0\" - 1920x1200",
      processor: "AMD Ryzen 5 6804HS",
      graphics: "AMD Radeon 726M",
      memory: "16 GB DDR5",
      image: Hp3,
      storage: "1024 GB SSD",
      weight: "1.71 Kg / 3.77 lb",
      os: "Windows 11 Pro",
      battery: "6.5 - 7 h",
      price: "$900",
    },
    {
      name: "Dell Inspiron 14 Plus",
      brand: 'Hp',
      screenSize: "14.0\" - 2240x1400",
      processor: "ARM-based Snapdragon X Plus",
      graphics: "ARM Snapdragon X Elite Adreno",
      memory: "16 GB DDR5",
      image: Hp4,
      storage: "512 GB SSD",
      weight: "1.46 Kg / 3.22 lb",
      os: "Windows 11 Home",
      battery: "6.3 - 6.7 h",
      price: "$1000",
    },
    {
      name: "Dell Inspiron 14 Plus",
      brand: 'Hp',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL i7-13620H",
      graphics: "INTEL UHD Graphics 10th gen",
      memory: "16 GB DDR5",
      image: Hp5,
      storage: "512 GB SSD",
      weight: "1.92 Kg / 4.23 lb",
      os: "Windows 11 Home",
      battery: "8.2 - 8.8 h",
      price: "$1509",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Hp',
      screenSize: "14.0\" - 1920x1080",
      processor: "INTEL i5-1335U",
      graphics: "INTEL Iris XE 80 EU",
      memory: "16 GB DDR5",
      image: Hp6,
      storage: "512 GB SSD",
      weight: "1.5 Kg / 3.31 lb",
      os: "Windows 11 Pro",
      battery: "4.4 - 4.7 h",
      price: "$991",
    },
    {
      name: "Dell Precision 15",
      brand: 'Samsung',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL i7-13700H",
      graphics: "INTEL Iris XE 96 EU",
      memory: "32 GB DDR5",
      image: Samsung1,
      storage: "2048 GB SSD",
      weight: "1.8 Kg / 3.96 lb",
      os: "Windows 11 Pro",
      battery: "9.4 - 10.1 h",
      price: "$1268",
    },
    {
      name: "Dell Latitude 15",
      brand: 'Samsung',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL i5-1235U",
      graphics: "INTEL Iris XE 96 EU",
      memory: "16 GB DDR5",
      image: Samsung2,
      storage: "512 GB SSD",
      weight: "1.59 Kg / 3.51 lb",
      os: "Windows 10 Pro",
      battery: "4.9 - 5.3 h",
      price: "$1038",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Samsung',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Samsung3,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Samsung',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Samsung4,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Samsung',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Samsung5,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Samsung',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Samsung6,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 15",
      brand: 'Lenovo',
      screenSize: "15.6\" - 1920x1080",
      processor: "INTEL i5-1235U",
      graphics: "INTEL Iris XE 96 EU",
      memory: "16 GB DDR5",
      image: Lenovo1,
      storage: "512 GB SSD",
      weight: "1.59 Kg / 3.51 lb",
      os: "Windows 10 Pro",
      battery: "4.9 - 5.3 h",
      price: "$1038",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Lenovo',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Lenovo2,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Lenovo',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Lenovo3,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Lenovo',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Lenovo4,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Lenovo',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Lenovo5,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Apple',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Apple1,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Apple',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Apple2,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Apple',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Apple3,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Apple',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Apple4,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Acer',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Acer1,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Acer',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Acer2,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
    {
      name: "Dell Latitude 14",
      brand: 'Acer',
      screenSize: "14.0\" - 2560x1600",
      processor: "ARM-based Snapdragon X Elite",
      graphics: "ARM Snapdragon X Elite",
      memory: "16 GB DDR5",
      image: Acer3,
      storage: "512 GB SSD",
      weight: "1.34 Kg / 3.17 lb",
      os: "Windows 11 Pro",
      battery: "6 - 6.4 h",
      price: "$1259",
    },
  ];
